### ISSUE TITLE
Gerber file error

### ISSUE THREAD

**Issue by fabiopili** [guix77/esphome-aldes-tone#1]
Hello, I've been exploring your project since I'll soon implement something similar for an Aldes Inspirair VMC unit. Thanks for sharing!

I believe there's an error with the Gerber file you shared. The ZIP contents are a bunch of PDF files that seem to contain personal information. I'd advise you to remove it and fix this issue as soon as possible.

**Comment by hugz** [comment]
Yes indeed, he just delete it. thx

**Comment by guix77** [comment]
Thanks @hugz and @fabiopili !!!
